language: java
jdk: oraclejdk8

install:
  - "sudo apt-get purge openjdk*"
  - "sudo add-apt-repository -y ppa:webupd8team/java"
  - "sudo apt-get update"
  - "sudo apt-get install oracle-java8-installer"

notifications:
  irc:
    channels: chat.freenode.net#bitsquare
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

env:
  global:
    # ORG_GRADLE_PROJECT_bitsquareDocsPassword
    - secure: "F2Al31+NsHMGztKYT9YlVHg6OBXXUdQisFJwI82vJLEjmuHoMBUdr3vC818xtxnW05CuiNtqtoMknXfDf3tYWWJ4YLDIU0vqAeDrHVSa6QCIUZqy/LTjyDoSIJ60B34TJ+XokSYPBXwwHUSmIAEnA6V23UueR7CVN4sH9ycXIWo="

after_success:
  "./gradlew publish"
